### ISSUE TITLE
Adapter stopped working

### ISSUE THREAD

**Issue by OberfragGER** [hash99/ioBroker.mieleathome#15]
Hi,
after changing... nothing. The Miele-Adapter is´nt working any longer. Its restarting now by hinself.

I put the logfile in here...
https://pastebin.com/kWtGD3QH

I stopped the adapter, delted the log, set the instanze on debug. startet the adapter. same problem. debug log is here
https://pastebin.com/MQRDH3yy

Any suggestions?

**Comment by OberfragGER** [comment]
Still not working.


host.raspberrypi4 | 2019-11-17 23:06:50.677 | info | instance system.adapter.mieleathome.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
host.raspberrypi4 | 2019-11-17 23:06:50.677 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.raspberrypi4 | 2019-11-17 23:06:50.677 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1143:12)
host.raspberrypi4 | 2019-11-17 23:06:50.677 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.raspberrypi4 | 2019-11-17 23:06:50.677 | error | Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
host.raspberrypi4 | 2019-11-17 23:06:50.676 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.raspberrypi4 | 2019-11-17 23:06:50.676 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.raspberrypi4 | 2019-11-17 23:06:50.676 | error | Caught by controller[0]: at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.raspberrypi4 | 2019-11-17 23:06:50.676 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.raspberrypi4 | 2019-11-17 23:06:50.676 | error | Caught by controller[0]: at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.raspberrypi4 | 2019-11-17 23:06:50.676 | error | Caught by controller[0]: at Request._callback (/opt/iobroker/node_modules/iobroker.mieleathome/utils/mieleathome.js:229:22)
host.raspberrypi4 | 2019-11-17 23:06:50.675 | error | Caught by controller[0]: TypeError: this.NRefreshToken is not a function

**Comment by Grizzelbee** [comment]
Please stop the adapter, delete your tokens under "mieleathome.0.Authorization.xxx" and set authorized to false. Restart the adapter.
This should help.

**Comment by OberfragGER** [comment]
solved and thanks a lot
